- name: Install SONM CDN node manager
  hosts: all

  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - docker.io
        - python-pip
        - nginx

    - name: install docker-py
      pip:
        name: docker-py
        version: 1.10.6


    - name: remove old node-manager instance
      docker_container:
        name: node-manager
        image: telminov/sonm-cdn-node-manager
        state: absent

    - name: create web-static dircetory
      file:
        path: /var/www/node-manager/static
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: create config directories
      file:
        path: "/var/docker/node-manager/{{ item }}"
        state: directory
        owner: root
        mode: 0700
      with_items:
        - conf
        - data
        - sonm/home

    - name: create node-manager config
      template:
        src: local_settings.py.jinja2
        dest: /var/docker/node-manager/conf/local_settings.py


    - name: copy SONM cli.yml
      copy:
        src: "{{ cli_yml_path }}"
        dest: /var/docker/node-manager/sonm/home/cli.yaml
        owner: root
        mode: 0600

    - name: copy SONM key store
      copy:
        src: "{{ key_store_path }}"
        dest: /var/docker/node-manager/sonm/


    - name: start node-manager
      docker_container:
        name: node-manager
        image: telminov/sonm-cdn-node-manager
        pull: yes
        ports:
          - 127.0.0.1:8081:80
        volumes:
          - /var/www/node-manager/static:/static
          - /var/docker/node-manager/data:/data
          - /var/docker/node-manager/conf:/conf
          - /var/docker/node-manager/sonm/home/:/root/.sonm/
          - /var/docker/node-manager/sonm/sonm-keystore:/etc/sonm/sonm-keystore


    - name: remove nginx default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: create nginx config
      template:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/node-manager

    - name: reload nginx
      service:
        name: nginx
        state: reloaded


    - name: Install SONM cli
      shell: docker exec -i node-manager bash -c './sonm-auto-deploy-consumer.sh'
      ignore_errors: true

    - name: Restart sonmnode
      shell: docker exec -i node-manager bash -c 'supervisorctl restart sonmnode'

    - name: Wait sonmnode start
      shell: sleep 5

    - name: Check sonmcli
      shell: docker exec -i node-manager bash -c 'sonmcli token balance'


    - name: Restart sonmnode
      shell: docker exec -i node-manager bash -c 'supervisorctl restart sonmnode'

    - name: Restart sonmnode
      shell: docker exec -i node-manager bash -c 'supervisorctl restart refresh_nodes'